# define a global platform for my project
platform :ios, '12.0'

target 'ContemPlant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContemPlant
  pod 'SwiftyUserDefaults', '4.0.0-alpha.1'
  pod 'Apollo', :podspec => 'custom-podspec/Apollo.podspec'
  pod 'SortedArray', :podspec => 'custom-podspec/SortedArray.podspec'
  pod 'JdenticonSwift', :podspec => 'custom-podspec/JdenticonSwift.podspec'

  pod 'SwiftOCR'
  pod 'ImageDetect'

  target 'ContemPlantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ContemPlantUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
