# define a global platform for my project
platform :ios, '12.0'

target 'ContemPlant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContemPlant
  pod 'SwiftyUserDefaults', '4.0.0-alpha.1'
  pod 'Apollo', :podspec => 'custom-podspec/Apollo.podspec'
  pod 'SortedArray', :podspec => 'custom-podspec/SortedArray.podspec'
  pod 'JdenticonSwift', :podspec => 'custom-podspec/JdenticonSwift.podspec'
  pod 'SwiftGif', :podspec => 'custom-podspec/SwiftGif.podspec'

  pod 'SwiftOCR'
  pod 'ImageDetect'
  
  pod 'UICircularProgressRing'

  target 'ContemPlantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ContemPlantUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
